import React from "react";
import CrudModule from "../components/CrudModule.jsx";

const module = (props) => function DomainModule() { return <CrudModule {...props} />; };
export const OrdersModule = module({ title: "Orders", description: "Live purchase orders and shipment risk records.", resource: "orders", fields: [
  { key: "id", label: "PO / ID" }, { key: "buyer", label: "Buyer" }, { key: "country", label: "Country" }, { key: "season", label: "Season" }, { key: "style", label: "Style" }, { key: "qty", label: "Quantity", type: "number" }, { key: "ship", label: "Ship date" }, { key: "risk", label: "Risk" }, { key: "status", label: "Status" },
] });
export const StaffModule = module({ title: "Staff", description: "Add, edit, and remove employees from the live roster.", resource: "staff", fields: [{ key: "name", label: "Name" }, { key: "title", label: "Title" }, { key: "dept", label: "Department" }, { key: "status", label: "Status" }] });
export const LeaveModule = module({ title: "Leave requests", description: "Live leave records with editable approval status.", resource: "leaveRequests", fields: [{ key: "name", label: "Name" }, { key: "dept", label: "Department" }, { key: "from", label: "From" }, { key: "to", label: "To" }, { key: "reason", label: "Reason" }, { key: "status", label: "Status" }] });
export const FinanceModule = module({ title: "Finance", description: "Live financial values used by reporting and executive views.", resource: "financials", singleton: true, fields: [{ key: "revenue", label: "Revenue", type: "number" }, { key: "cogs", label: "COGS", type: "number" }, { key: "ebitda", label: "EBITDA", type: "number" }, { key: "cashFlow", label: "Cash flow", type: "number" }, { key: "stockValue", label: "Stock value", type: "number" }, { key: "complianceScore", label: "Compliance score", type: "number" }] });
export const ComplianceModule = module({ title: "Compliance", description: "Live certification status and attachments metadata.", resource: "certifications", fields: [{ key: "name", label: "Certificate" }, { key: "note", label: "Note" }, { key: "status", label: "Status" }, { key: "file", label: "File", required: false }] });
export const DebitNotesModule = module({ title: "Debit notes", description: "Live buyer deductions and claims.", resource: "debitNotes", fields: [{ key: "season", label: "Season" }, { key: "buyer", label: "Buyer" }, { key: "po", label: "PO", required: false }, { key: "amount", label: "Amount", type: "number" }, { key: "reason", label: "Reason" }, { key: "date", label: "Date" }] });
export const CapasModule = module({ title: "CAPAs", description: "Live corrective and preventive actions.", resource: "capas", fields: [{ key: "season", label: "Season" }, { key: "buyer", label: "Buyer" }, { key: "po", label: "PO", required: false }, { key: "issue", label: "Issue" }, { key: "action", label: "Action" }, { key: "status", label: "Status" }, { key: "date", label: "Date" }] });